#! /bin/csh
export SRD_Dx=0.005
export SRD_Dy=0.1
export SRD_Da=0.00000000000001
export SRD_a=0.01
export SRD_b=1.5
export SRD_c=1.8
export SRD_d=0.07
export SRD_initA=8.0
export SRD_B=1.0
export SRD_Kp=18.0
export SRD_Su=1.0
export SRD_Kd=0.15
export SRD_Xth=0.0
export SRD_radius=0.25
export SRD_delta_t=0.05
export SRD_endtime=10000.0
export SRD_pic_freq=100
export SRD_Area_Growth=0.001
export SRD_moves_per_growth_step=1
export SRD_growth_frequency=10
export SRD_growth_onset=5000
export SRD_length_tolerance=2.0
export SRD_random_seed=9 
export SRD_triangulation=../disk_triangulate/T20
export SRD_old_result_dir=res091071
export SRD_new_result_dir=res1216
export SRD_refinement_freq=10
export SRD_pickuprun=0
export SRD_undumpfilename=dump192

../disk_triangulate/triangulate 20 >! ../disk_triangulate/T20

mkdir res091071
make
#cd  /home/david/3d/philtrans
nohup ./growth_srd
